Repository dropwizard/metrics, pull requests merged in 2020-11, with the labels that each got.

#1697 Run SonarCloud analysis only when SONAR_TOKEN is available
  .github/workflows/maven.yml
Labels: github_actions

#1708 Upgrade to Jackson 2.9.10.6
  metrics-json/pom.xml
  metrics-servlets/pom.xml
Labels: dependencies, java, security

#1710 Enforce lower/upper limit on frequency parameter of CPU profile servlet
  metrics-servlets/src/main/java/com/codahale/metrics/servlets/CpuProfileServlet.java
Labels: improvement

#1702 Allow configuration of the maxlength of names sent to collectd
  metrics-collectd/src/main/java/com/codahale/metrics/collectd/CollectdReporter.java
  metrics-collectd/src/main/java/com/codahale/metrics/collectd/MetaData.java
  metrics-collectd/src/main/java/com/codahale/metrics/collectd/Sanitize.java
  metrics-collectd/src/test/java/com/codahale/metrics/collectd/CollectdReporterTest.java
  metrics-collectd/src/test/java/com/codahale/metrics/collectd/SanitizeTest.java
Labels: improvement
