Repository dropwizard/metrics, pull requests merged in 2020-05, with the labels that each got.

#1571 Upgrade to Jackson 2.9.10.4
  metrics-json/pom.xml
  metrics-servlets/pom.xml
Labels: dependencies

#1575 Ensure datagram socket in collectd tests is bound before sending
  metrics-collectd/src/test/java/com/codahale/metrics/collectd/Receiver.java
Labels: improvement

#1576 Support sending Graphite metric attributes as tags
  metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
  metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
Labels: improvement

#1573 Support custom floating point formatter in Graphite reporter
  metrics-graphite/src/main/java/com/codahale/metrics/graphite/GraphiteReporter.java
  metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
Labels: feature

#1544 Improve tick overflow handling in SlidingTimeWindowReservoir
  metrics-core/src/main/java/com/codahale/metrics/SlidingTimeWindowReservoir.java
  metrics-core/src/test/java/com/codahale/metrics/SlidingTimeWindowReservoirTest.java
Labels: improvement

#1578 Adding PATH_AND_METHOD naming strategy
  metrics-httpclient/src/main/java/com/codahale/metrics/httpclient/HttpClientMetricNameStrategies.java
  metrics-httpclient/src/test/java/com/codahale/metrics/httpclient/HttpClientMetricNameStrategiesTest.java
Labels: improvement

#1579 Report metrics when stopping ScheduledReporter
  metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
  metrics-core/src/test/java/com/codahale/metrics/ScheduledReporterTest.java
  metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteReporterTest.java
Labels: bug

#1586 Add exception type to HealthCheck JSON representation
  metrics-json/src/main/java/com/codahale/metrics/json/HealthCheckModule.java
  metrics-json/src/test/java/com/codahale/metrics/json/HealthCheckModuleTest.java
Labels: improvement

#1590 Avoid queuing up report tasks in ScheduledReporter
  metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
  metrics-core/src/test/java/com/codahale/metrics/ScheduledReporterTest.java
Labels: improvement
