Repository dropwizard/metrics, pull requests merged in 2020-10, with the labels that each got.

#1660 Add missing blank in documentation
  docs/source/manual/jetty.rst
Labels: documentation

#1654 Fix ExponentiallyDecayingReservoir constant rescaling
  metrics-core/src/main/java/com/codahale/metrics/ExponentiallyDecayingReservoir.java
  metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java
  metrics-core/src/test/java/com/codahale/metrics/ManualClock.java
Labels: bug

#1665 Remove NOTICE file
  NOTICE
Labels: documentation

#1671 Adds separator to csv header (#1670)
  metrics-core/src/main/java/com/codahale/metrics/CsvReporter.java
  metrics-core/src/test/java/com/codahale/metrics/CsvReporterTest.java
Labels: bug

#1656 Implement LockFreeExponentiallyDecayingReservoir
  metrics-benchmarks/src/main/java/com/codahale/metrics/benchmarks/ReservoirBenchmark.java
  metrics-core/src/main/java/com/codahale/metrics/LockFreeExponentiallyDecayingReservoir.java
  metrics-core/src/test/java/com/codahale/metrics/ExponentiallyDecayingReservoirTest.java
Labels: improvement

#1685 Remove metrics from registry when stopping managed object
  metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHandler.java
  metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedQueuedThreadPool.java
  metrics-jetty9/src/test/java/com/codahale/metrics/jetty9/InstrumentedHandlerTest.java
  metrics-jetty9/src/test/java/com/codahale/metrics/jetty9/InstrumentedQueuedThreadPoolTest.java
Labels: bug

#1687 Add parameter for customizing reservoir in timers in metrics-jersey2
  metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/MetricsFeature.java
  metrics-jersey2/src/test/java/com/codahale/metrics/jersey2/CustomReservoirImplementationTest.java
Labels: improvement

#1688 CachedGauge: Fix reloading when Clock's time is negative
  metrics-core/src/main/java/com/codahale/metrics/CachedGauge.java
  metrics-core/src/test/java/com/codahale/metrics/CachedGaugeTest.java
Labels: bug
