Repository dropwizard/metrics, pull requests merged in 2021-12, with the labels that each got.

#2285 Update repository URLs for new OSSRH Sonatype instance
  pom.xml
Labels: task

#2286 Update repository URLs for new OSSRH Sonatype instance
  pom.xml
Labels: task

#2287 Update repository URLs for new OSSRH Sonatype instance
  pom.xml
Labels: task

#2281 drop useless configuration for m-bundle-p 5.1.3
  pom.xml
Labels: improvement

#2309 Enable separate minor patches and Dependency Dashboard in Renovate
  renovate.json
Labels: dependencies

#2310 Remove duplicate Jackson version properties
  metrics-jakarta-servlets/pom.xml
  metrics-json/pom.xml
  metrics-servlets/pom.xml
  pom.xml
Labels: dependencies

#2337 Migrate to official Maven wrapper
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: dependencies

#2336 Migrate to official Maven wrapper
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: dependencies

#2338 Migrate to official Maven wrapper
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: dependencies
