Repository dropwizard/metrics, pull requests merged in 2021-01, with the labels that each got.

#1730 Add support for jakarta.servlet
  metrics-bom/pom.xml
  metrics-jakarta-servlet/pom.xml
  metrics-jakarta-servlet/src/main/java/io/dropwizard/metrics/servlet/AbstractInstrumentedFilter.java
  metrics-jakarta-servlet/src/main/java/io/dropwizard/metrics/servlet/InstrumentedFilter.java
  metrics-jakarta-servlet/src/main/java/io/dropwizard/metrics/servlet/InstrumentedFilterContextListener.java
  metrics-jakarta-servlet/src/test/java/io/dropwizard/metrics/servlet/InstrumentedFilterContextListenerTest.java
  metrics-jakarta-servlets/pom.xml
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/AdminServlet.java
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/CpuProfileServlet.java
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/HealthCheckServlet.java
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/MetricsServlet.java
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/PingServlet.java
  metrics-jakarta-servlets/src/main/java/io/dropwizard/metrics/servlets/ThreadDumpServlet.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/AbstractServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/AdminServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/CpuProfileServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/HealthCheckServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/MetricsServletContextListenerTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/MetricsServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/PingServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/ThreadDumpServletTest.java
  metrics-jakarta-servlets/src/test/java/io/dropwizard/metrics/servlets/experiments/ExampleServer.java
  pom.xml
Labels: improvement

#1732 Add no-op implementation of MetricRegistry
  metrics-core/src/main/java/com/codahale/metrics/NoopMetricRegistry.java
  metrics-core/src/main/java/com/codahale/metrics/Timer.java
  metrics-core/src/test/java/com/codahale/metrics/NoopMetricRegistryTest.java
Labels: feature

#1733 Upgrade to Jackson Databind 2.9.10.8
  pom.xml
Labels: dependencies, java

#1721 Properly reconnect to Graphite via TCP
  metrics-graphite/src/main/java/com/codahale/metrics/graphite/Graphite.java
  metrics-graphite/src/test/java/com/codahale/metrics/graphite/GraphiteTest.java
Labels: improvement

#1745 Upgrade metrics-jersey2 to Jersey 2.33
  metrics-jersey2/pom.xml
  pom.xml
Labels: dependencies, java
