Repository dropwizard/metrics, pull requests merged in 2021-05, with the labels that each got.

#1905 Improve docs for `AdminServlet` et al
  docs/source/manual/servlets.rst
Labels: documentation

#1927 Allow customizing `ClientConnectionManager` for Apache HttpClient 5
  metrics-httpclient5/src/main/java/com/codahale/metrics/httpclient5/InstrumentedHttpAsyncClients.java
  metrics-httpclient5/src/test/java/com/codahale/metrics/httpclient5/InstrumentedHttpAsyncClientsTest.java
Labels: improvement

#1928 Add ThreadPoolExecutor and ForkJoinPool metrics
  metrics-core/src/main/java/com/codahale/metrics/InstrumentedExecutorService.java
  metrics-core/src/test/java/com/codahale/metrics/InstrumentedExecutorServiceTest.java
Labels: improvement

#1967 Explicitly declare all dependencies of sub-modules
  metrics-benchmarks/pom.xml
  metrics-caffeine/pom.xml
  metrics-collectd/pom.xml
  metrics-core/pom.xml
  metrics-ehcache/pom.xml
  metrics-graphite/pom.xml
  metrics-healthchecks/pom.xml
  metrics-httpasyncclient/pom.xml
  metrics-httpclient/pom.xml
  metrics-httpclient5/pom.xml
  metrics-jcache/pom.xml
  metrics-jdbi/pom.xml
  metrics-jdbi3/pom.xml
  metrics-jersey2/pom.xml
  metrics-jetty9/pom.xml
  metrics-jmx/pom.xml
  metrics-json/pom.xml
  metrics-jvm/pom.xml
  metrics-log4j2/pom.xml
  metrics-logback/pom.xml
  metrics-servlet/pom.xml
  metrics-servlets/pom.xml
  pom.xml
Labels: bug

#1969 Explicitly declare all dependencies of sub-modules
  metrics-benchmarks/pom.xml
  metrics-caffeine/pom.xml
  metrics-caffeine3/pom.xml
  metrics-collectd/pom.xml
  metrics-core/pom.xml
  metrics-ehcache/pom.xml
  metrics-graphite/pom.xml
  metrics-healthchecks/pom.xml
  metrics-httpasyncclient/pom.xml
  metrics-httpclient/pom.xml
  metrics-httpclient5/pom.xml
  metrics-influxdb/pom.xml
  metrics-jakarta-servlet/pom.xml
  metrics-jakarta-servlets/pom.xml
  metrics-jcache/pom.xml
  metrics-jdbi/pom.xml
  metrics-jdbi3/pom.xml
  metrics-jersey2/pom.xml
  metrics-jersey3/pom.xml
  metrics-jetty10/pom.xml
  metrics-jetty11/pom.xml
  metrics-jetty9/pom.xml
  metrics-jmx/pom.xml
  metrics-json/pom.xml
  metrics-jvm/pom.xml
  metrics-legacy-adapter-healthchecks/pom.xml
  metrics-legacy-adapter/pom.xml
  metrics-log4j2/pom.xml
  metrics-logback/pom.xml
  metrics-servlet/pom.xml
  metrics-servlets/pom.xml
  pom.xml
Labels: bug

#1968 Explicitly declare all dependencies of sub-modules
  metrics-benchmarks/pom.xml
  metrics-caffeine/pom.xml
  metrics-caffeine3/pom.xml
  metrics-collectd/pom.xml
  metrics-core/pom.xml
  metrics-ehcache/pom.xml
  metrics-graphite/pom.xml
  metrics-healthchecks/pom.xml
  metrics-httpasyncclient/pom.xml
  metrics-httpclient/pom.xml
  metrics-httpclient5/pom.xml
  metrics-jakarta-servlet/pom.xml
  metrics-jakarta-servlets/pom.xml
  metrics-jcache/pom.xml
  metrics-jdbi/pom.xml
  metrics-jdbi3/pom.xml
  metrics-jersey2/pom.xml
  metrics-jersey3/pom.xml
  metrics-jetty10/pom.xml
  metrics-jetty11/pom.xml
  metrics-jetty9/pom.xml
  metrics-jmx/pom.xml
  metrics-json/pom.xml
  metrics-jvm/pom.xml
  metrics-log4j2/pom.xml
  metrics-logback/pom.xml
  metrics-servlet/pom.xml
  metrics-servlets/pom.xml
  pom.xml
Labels: bug
