Repository dropwizard/metrics, pull requests merged in 2022-12, with the labels that each got.

#3021 Merge Renovate PRs automatically (patch only)
  renovate.json
Labels: dependencies

#2931 Allow override of scheduler
  metrics-core/src/main/java/com/codahale/metrics/ScheduledReporter.java
Labels: improvement

#3041 Add support for Jersey 3.1.x
  metrics-jersey31/pom.xml
  metrics-jersey31/src/main/java/io/dropwizard/metrics/jersey31/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey31/src/main/java/io/dropwizard/metrics/jersey31/MetricsFeature.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/CustomReservoirImplementationTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonFilterMetricsJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsExceptionMeteredPerClassJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsMeteredPerClassJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsResponseMeteredPerClassJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsTimedPerClassJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/TestClock.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/exception/TestException.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/exception/mapper/TestExceptionMapper.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedFilteredResource.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResource.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResourceExceptionMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResourceMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResourceResponseMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResourceTimedPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResource.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResourceExceptionMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResourceMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResourceResponseMeteredPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResourceTimedPerClass.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/TestRequestFilter.java
  pom.xml
Labels: feature

#3047 Revert "Update logback13.version to v1.4.5"
  metrics-logback13/pom.xml
Labels: bug

#3048 Fix incorrect javaModuleName property in metrics-logback13
  metrics-logback13/pom.xml
Labels: bug

#3050 Fix incorrect javaModuleName property in metrics-logback13
  metrics-logback13/pom.xml
Labels: bug

#3060 Bump Jackson to version 2.14.1
  pom.xml
Labels: dependencies, java
