Repository dropwizard/metrics, pull requests merged in 2022-06, with the labels that each got.

#2658 Generate SBOM using CycloneDX Maven plugin
  pom.xml
Labels: task, security

#2657 Generate SBOM using CycloneDX Maven plugin
  pom.xml
Labels: task, security

#2613 chore: renovate bot setting to pin actions to a full length commit SHA
  renovate.json
Labels: security, github_actions

#2642 Add a more type safe way of registering gauges
  metrics-core/src/main/java/com/codahale/metrics/InstrumentedExecutorService.java
  metrics-core/src/main/java/com/codahale/metrics/MetricRegistry.java
  metrics-core/src/test/java/com/codahale/metrics/MetricRegistryTest.java
  metrics-ehcache/src/main/java/com/codahale/metrics/ehcache/InstrumentedEhcache.java
  metrics-ehcache/src/test/java/com/codahale/metrics/ehcache/InstrumentedEhcacheTest.java
  metrics-httpasyncclient/src/main/java/com/codahale/metrics/httpasyncclient/InstrumentedNClientConnManager.java
  metrics-httpclient/src/main/java/com/codahale/metrics/httpclient/InstrumentedHttpClientConnectionManager.java
  metrics-httpclient/src/test/java/com/codahale/metrics/httpclient/InstrumentedHttpClientConnectionManagerTest.java
  metrics-httpclient5/src/main/java/com/codahale/metrics/httpclient5/InstrumentedAsyncClientConnectionManager.java
  metrics-httpclient5/src/main/java/com/codahale/metrics/httpclient5/InstrumentedHttpClientConnectionManager.java
  metrics-httpclient5/src/test/java/com/codahale/metrics/httpclient5/InstrumentedAsyncClientConnectionManagerTest.java
  metrics-httpclient5/src/test/java/com/codahale/metrics/httpclient5/InstrumentedHttpClientConnectionManagerTest.java
  metrics-jetty10/src/main/java/io/dropwizard/metrics/jetty10/InstrumentedQueuedThreadPool.java
  metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedQueuedThreadPool.java
  metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedQueuedThreadPool.java
  metrics-jmx/src/test/java/com/codahale/metrics/jmx/JmxReporterTest.java
Labels: improvement
