Repository dropwizard/metrics, pull requests merged in 2023-09, with the labels that each got.

#3571 Build with Java 21
  .github/workflows/maven.yml
  .github/workflows/trigger-release.yml
  metrics-core/pom.xml
  metrics-core/src/test/java/io/dropwizard/metrics5/ConsoleReporterTest.java
  metrics-legacy-adapter/pom.xml
  metrics-legacy-adapter/src/test/java/com/codahale/metrics/ConsoleReporterTest.java
  pom.xml
Labels: dependencies, java

#3579 Build documentation with Sphinx <7
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug

#3580 Build documentation with Sphinx <7
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug, documentation, dependencies

#3570 Build with Java 21
  .github/workflows/maven.yml
  .github/workflows/trigger-release.yml
  metrics-core/pom.xml
  metrics-core/src/test/java/com/codahale/metrics/ConsoleReporterTest.java
  pom.xml
Labels: dependencies, java

#3531 Support setting `ThreadFactory` for Jetty 10, 11 and 12
  metrics-jetty10/src/main/java/io/dropwizard/metrics/jetty10/InstrumentedQueuedThreadPool.java
  metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedQueuedThreadPool.java
  metrics-jetty12/src/main/java/io/dropwizard/metrics/jetty12/InstrumentedQueuedThreadPool.java
Labels: improvement

#3578 Fix Jetty 12/Jakarta EE 10 InstrumentedEE10Handler
  metrics-jetty12-ee10/src/main/java/io/dropwizard/metrics/jetty12/ee10/InstrumentedEE10Handler.java
  metrics-jetty12-ee10/src/test/java/io/dropwizard/metrics/jetty12/ee10/InstrumentedEE10HandlerTest.java
Labels: bug

#3594 Use new maven-javadoc-plugin legacyMode
  .github/workflows/maven.yml
  pom.xml
Labels: bug

#3600 Use new maven-javadoc-plugin legacyMode
  .github/workflows/maven.yml
  pom.xml
Labels: bug
