Repository dropwizard/metrics, pull requests merged in 2023-02, with the labels that each got.

#3116 Add ResponseMeteredLevel parameter to ResponseMetered annotation jersey31
  metrics-jersey31/src/main/java/io/dropwizard/metrics/jersey31/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/SingletonMetricsResponseMeteredPerClassJerseyTest.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedResource.java
  metrics-jersey31/src/test/java/io/dropwizard/metrics/jersey31/resources/InstrumentedSubResourceResponseMeteredPerClass.java
Labels: feature

#3115 Add parameter ResponseMeteredLevel to the ResponseMetered annotation jersey3
  metrics-jersey3/src/main/java/com/codahale/metrics/jersey3/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey3/src/test/java/com/codahale/metrics/jersey3/SingletonMetricsJerseyTest.java
  metrics-jersey3/src/test/java/com/codahale/metrics/jersey3/SingletonMetricsResponseMeteredPerClassJerseyTest.java
  metrics-jersey3/src/test/java/com/codahale/metrics/jersey3/resources/InstrumentedResource.java
  metrics-jersey3/src/test/java/com/codahale/metrics/jersey3/resources/InstrumentedSubResourceResponseMeteredPerClass.java
Labels: feature

#3151 Remove module for jDBI 2.x
  docs/source/manual/jdbi.rst
  metrics-bom/pom.xml
  metrics-jdbi/pom.xml
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/InstrumentedTimingCollector.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/BasicSqlNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/ContextNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/DelegatingStatementNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/NaiveNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/NameStrategies.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/ShortNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/SmartNameStrategy.java
  metrics-jdbi/src/main/java/io/dropwizard/metrics5/jdbi/strategies/StatementNameStrategy.java
  metrics-jdbi/src/test/java/io/dropwizard/metrics5/jdbi/InstrumentedTimingCollectorTest.java
  pom.xml
Labels: dependencies

#3150 Remove module for Caffeine 2.x
  docs/source/manual/caffeine.rst
  metrics-bom/pom.xml
  metrics-caffeine/pom.xml
  metrics-caffeine/src/main/java/io/dropwizard/metrics5/caffeine/MetricsStatsCounter.java
  metrics-caffeine/src/test/java/io/dropwizard/metrics5/caffeine/MetricsStatsCounterTest.java
  pom.xml
Labels: dependencies

#3152 Remove module for Jetty 9.x
  docs/source/manual/jetty.rst
  metrics-bom/pom.xml
  metrics-jetty10/pom.xml
  metrics-jetty9/pom.xml
  metrics-jetty9/src/main/java/io/dropwizard/metrics5/jetty9/InstrumentedConnectionFactory.java
  metrics-jetty9/src/main/java/io/dropwizard/metrics5/jetty9/InstrumentedHandler.java
  metrics-jetty9/src/main/java/io/dropwizard/metrics5/jetty9/InstrumentedHttpChannelListener.java
  metrics-jetty9/src/main/java/io/dropwizard/metrics5/jetty9/InstrumentedQueuedThreadPool.java
  metrics-jetty9/src/test/java/io/dropwizard/metrics5/jetty9/InstrumentedConnectionFactoryTest.java
  metrics-jetty9/src/test/java/io/dropwizard/metrics5/jetty9/InstrumentedHandlerTest.java
  metrics-jetty9/src/test/java/io/dropwizard/metrics5/jetty9/InstrumentedHttpChannelListenerTest.java
  metrics-jetty9/src/test/java/io/dropwizard/metrics5/jetty9/InstrumentedQueuedThreadPoolTest.java
  metrics-servlets/pom.xml
  metrics-servlets/src/test/java/io/dropwizard/metrics5/servlets/experiments/ExampleServer.java
  pom.xml
Labels: dependencies

#3153 Remove module for Logback 1.2.x
  docs/source/manual/logback.rst
  metrics-bom/pom.xml
  metrics-logback/pom.xml
  metrics-logback/src/main/java/io/dropwizard/metrics5/logback/InstrumentedAppender.java
  metrics-logback/src/test/java/io/dropwizard/metrics5/logback/InstrumentedAppenderTest.java
  pom.xml
Labels: dependencies

#3154 Add missing modules to metrics-bom
  metrics-bom/pom.xml
Labels: bug

#3133 Add response code meters for jetty9
  metrics-jetty9/pom.xml
  metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHandler.java
  metrics-jetty9/src/main/java/com/codahale/metrics/jetty9/InstrumentedHttpChannelListener.java
  metrics-jetty9/src/test/java/com/codahale/metrics/jetty9/InstrumentedHandlerTest.java
  metrics-jetty9/src/test/java/com/codahale/metrics/jetty9/InstrumentedHttpChannelListenerTest.java
Labels: feature

#3174 Add detailed response code meters for Jetty 10.x
  metrics-jetty10/pom.xml
  metrics-jetty10/src/main/java/io/dropwizard/metrics/jetty10/InstrumentedHandler.java
  metrics-jetty10/src/main/java/io/dropwizard/metrics/jetty10/InstrumentedHttpChannelListener.java
  metrics-jetty10/src/test/java/io/dropwizard/metrics/jetty10/InstrumentedHandlerTest.java
  metrics-jetty10/src/test/java/io/dropwizard/metrics/jetty10/InstrumentedHttpChannelListenerTest.java
Labels: feature

#3175 Add detailed response code meters for Jetty 11.x
  metrics-jetty11/pom.xml
  metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedHandler.java
  metrics-jetty11/src/main/java/io/dropwizard/metrics/jetty11/InstrumentedHttpChannelListener.java
  metrics-jetty11/src/test/java/io/dropwizard/metrics/jetty11/InstrumentedHandlerTest.java
  metrics-jetty11/src/test/java/io/dropwizard/metrics/jetty11/InstrumentedHttpChannelListenerTest.java
Labels: feature

#3125 [JVM] Fix maximum/total memory calculation
  metrics-jvm/src/main/java/com/codahale/metrics/jvm/MemoryUsageGaugeSet.java
  metrics-jvm/src/test/java/com/codahale/metrics/jvm/MemoryUsageGaugeSetTest.java
Labels: improvement

#3179 Fix potential NPE in InstrumentedResourceMethodApplicationListener
  metrics-jersey2/src/main/java/com/codahale/metrics/jersey2/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey3/src/main/java/com/codahale/metrics/jersey3/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey31/src/main/java/io/dropwizard/metrics/jersey31/InstrumentedResourceMethodApplicationListener.java
Labels: bug

#3178 Fix potential NPE in InstrumentedResourceMethodApplicationListener
  metrics-jersey2/src/main/java/io/dropwizard/metrics5/jersey2/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey3/src/main/java/io/dropwizard/metrics5/jersey3/InstrumentedResourceMethodApplicationListener.java
  metrics-jersey31/src/main/java/io/dropwizard/metrics5/jersey31/InstrumentedResourceMethodApplicationListener.java
Labels: bug
