Repository dropwizard/metrics, pull requests merged in 2023-08, with the labels that each got.

#3500 Add Qodana workflow
  .github/workflows/qodana.yml
  qodana.yaml
Labels: github_actions

#3501 Add Qodana workflow
  .github/workflows/qodana.yml
  qodana.yaml
Labels: github_actions

#3515 Add modules to support Jetty 12
  metrics-bom/pom.xml
  metrics-jetty12-ee10/pom.xml
  metrics-jetty12-ee10/src/main/java/io/dropwizard/metrics/jetty12/ee10/InstrumentedEE10Handler.java
  metrics-jetty12-ee10/src/test/java/io/dropwizard/metrics/jetty12/ee10/InstrumentedEE10HandlerTest.java
  metrics-jetty12/pom.xml
  metrics-jetty12/src/main/java/io/dropwizard/metrics/jetty12/AbstractInstrumentedHandler.java
  metrics-jetty12/src/main/java/io/dropwizard/metrics/jetty12/InstrumentedConnectionFactory.java
  metrics-jetty12/src/main/java/io/dropwizard/metrics/jetty12/InstrumentedQueuedThreadPool.java
  metrics-jetty12/src/test/java/io/dropwizard/metrics/jetty12/InstrumentedConnectionFactoryTest.java
  metrics-jetty12/src/test/java/io/dropwizard/metrics/jetty12/InstrumentedQueuedThreadPoolTest.java
  pom.xml
Labels: feature

#3523 Build releases with Java 17
  .github/workflows/release.yml
Labels: java

#3524 Build releases with Java 17
  .github/workflows/release.yml
Labels: java
